### PR TITLE
feat: self-contained releases support

### PR DESCRIPTION
**Pull request by LiquidTheDangerous**
Support for releases without external (shared object) dependencies

### CODE REVIEW

**Comment by xvzc** [comment]
This is no longer used since we use github actions to make releases

**Comment by xvzc** [comment]
Will there be any problem if we just add the `CGO_EABLED` for every release? because we already have to create 8 releases . If we make another set of releases that have `CGO_ENABLED` variable, then we should create 16 releases everytime.

**Comment by shurakr** [comment]
Yes, sure.

Best regards,
Alex

вс, 18 авг. 2024 г., 11:31 . ***@***.***>:

**Comment by LiquidTheDangerous** [comment]
@xvzc There shouldn't be any problems, on the contrary, the releases will be more portable. The only downside is that the binary size will increase.

**Pull request closed without merging**
