### PR TITLE
docs: add links to distro packages

### PR DESCRIPTION
**Pull request by txtsd**
Adds links to distro packages for distro compliant installation methods

### CODE REVIEW

**Comment by txtsd** [comment]
When I rebase this, do you want me to add the links to _docs/INSTALL.md or in README.md under Installation?

**Comment by xvzc** [comment]
Please add those information to INSTALL.me

**Comment by txtsd** [comment]
Rebased. Ready for review now.

**Comment by xvzc** [comment]
I'm sorry but i just decided to showing packaging status on the README.md instead of adding installation guide for every single package managers. Because then we have to manage tons of instructions for every other package managers.

**Comment by txtsd** [comment]
The repology idea is excellent!

**Pull request closed without merging**
