### PR TITLE
feat: add transparent proxy flag

### PR DESCRIPTION
**Pull request by zorn-v**
You can use it in some router with iptables rule like
```
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8080
```

### CODE REVIEW

**Comment by Ledorub** [comment]
It doesn't work on my machine.
`-debug -transparent`:
```
2024-08-28T15:14:46+03:00 ERR [PROXY] Get SO_ORIGINAL_DST error: protocol not available
```

`-debug -transparent -addr '::1'`:
```
2024-08-28T15:19:48+03:00 ERR [PROXY] Get SO_ORIGINAL_DST error: invalid argument
```

**Comment by zorn-v** [comment]
How your redirect firewall (nft/iptables) rule looks like ?

**Comment by Ledorub** [comment]
I re-read your top comment. Am I right that it is for installation on routers only? If so, then my first comment is irrelevant.

**Comment by zorn-v** [comment]
> Am I right that it is for installation on routers only?

You can forward traffic on local machine also. 
Something like this https://docs.mitmproxy.org/stable/howto-transparent/#work-around-to-redirect-traffic-originating-from-the-machine-itself

**Comment by LiquidTheDangerous** [comment]
@zorn-v It should be guaranteed that the proxy in transparent mode will receive a TLS handshake first. There is no guarantee.

**Comment by zorn-v** [comment]
I tested it on entware (openwrt like) and all works fine

**Comment by harryqt** [comment]
> ```
> iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8080
> ```

I was planning to do something like this. Is this PR needed for it to work?

**Comment by zorn-v** [comment]
> Is this PR needed for this to work?

Yes, and you need run it with `-transparent` option

**Comment by xvzc** [comment]
Do we really need this instead of setting proxy? I personally think this PR is a bit out of concept.

**Comment by harryqt** [comment]
> Do we really need this instead of setting proxy?

I've a RaspberryPi at home which works as router, and other WiFi routers connected as bridge to it.

I don't like setting up proxies for each and every device/browsers. By using that iptables redirect rules, I don't have to setup proxies anymore, all the devices will be DPI proof by default.

**Comment by zorn-v** [comment]
@xvzc
If you do not like hack with reflection, it also possible to do it via "IP_TRANSPARENT"
But then need to do more tricky config firewall rules

**Comment by zorn-v** [comment]
> the purpose of our project

I got it. discuss about 'quiet' flag is purpose of this project.

**Comment by zorn-v** [comment]
@xvzc happy discussions

**Comment by zorn-v** [comment]
Sorry for pranks, but does not this tool should not BYPASS goverment restrictions ?
As I can see, it only for @xvzc "I'm sexy and I'm know it"
I can be wrong

**Pull request closed without merging**
