### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by Viktor45**
Add simple Dockerfile for latest version

### CODE REVIEW

**Comment by DesSolo** [comment]
I think it's worth using a multi-stage build

**Comment by Viktor45** [comment]
I don't mind if you write your own, there was just no option at all and I had to write the simplest one for deployment on my server and share it

**Comment by xvzc** [comment]
I think it's better to do something like below
```dockerfile
FROM golang:alpine

WORKDIR /go

RUN go install github.com/xvzc/SpoofDPI/cmd/spoof-dpi@latest

ENV PATH="${HOME}/.spoof-dpi/bin:${PATH}"

EXPOSE 8080
```

this way, we can run it inside the container like this

```bash
$ docker build ./ -t spoof-dpi:latest
$ docker run -ti spoof-dpi:latest spoof-dpi --timeout 2000 --debug
```

**Comment by DesSolo** [comment]
```Dockerfile
FROM golang:1.21 as builder

WORKDIR /build

ADD . .

# or create Makefile target like `make build-docker`
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o spoof-dpi -ldflags="-s -w" cmd/spoof-dpi/main.go

FROM alpine:3.16

WORKDIR /spoof-dpi

COPY --from=builder /build/spoof-dpi .

ENTRYPOINT ["./spoof-dpi"]
```

**Comment by yesworld** [comment]
Docker is a good idea!

**Comment by Viktor45** [comment]
Proposed more simple Dockerfile as suggested 👍

**Pull request merged**
