### PR TITLE
Adds support for pattern file

### PR DESCRIPTION
**Pull request by Ledorub**
This PR adds support for pattern file. The file can be used to provide a custom list of regex patterns or domains (e.g. from GoodbyeDPI) that must be proxified.

- The file path is specified via a new option `-pattern-file`.
- The file should contain one pattern per line.
- Patterns from the file are **merged** with patterns provided via `-pattern` option.

### CODE REVIEW

**Comment by xvzc** [comment]
Please rebase and force push to the main branch

**Comment by Ledorub** [comment]
The feature was implemented on top of the latest main commit, so I fast-forwarded the main branch of the fork, but there is no way to update the source branch of the PR. Should I close this one and create a new one from fork/main?

**Comment by xvzc** [comment]
I'm sorry to bother you but there was another merge to main branch. so you should rebase and force push again.

**Comment by Ledorub** [comment]
Force-pushed to the fork's `main`.

**Comment by Ledorub** [comment]
Could you elaborate? I checked the fork and there is `3 commits ahead of xvzc/SpoofDPI:main` message at the top of the page when the main branch is selected. Commit hashes of the `main` and `fork/main` match.  So, the history seems linear.

**Comment by xvzc** [comment]
Okay got it.

**Comment by Ledorub** [comment]
Rebased `fork/main` on top of `origin/main` ([ffdd935](https://github.com/xvzc/SpoofDPI/commit/ffdd93539c6c03d1b0609a44de3a8376a17a7f77)).

**Comment by Ledorub** [comment]
Rebased `fork/main` on top of `origin/main` (9edb4dc).

**Comment by xvzc** [comment]
Your commits don't seem to have been properly rebased yet.

**Comment by xvzc** [comment]
image

**Pull request closed without merging**
