### PR TITLE
chore: refactor logging

### PR DESCRIPTION
**Pull request by Ledorub**
Refactored logging:
- Switched from logrus to zerolog.
- Made the most important functions accept `context.Context` as an arg.
- Made `main` create a context and pass it downstream.
- Moved scope (e.g. `[HTTPS]`, `[DNS]`, etc.) to context and transferred responsibility of including it into messages to logger.
- Implemented trace id generation and logging.

### CODE REVIEW

**Comment by xvzc** [comment]
Great work, but how about we make a seesion package that wraps `context.Context`

```go
// proxy/session.go
type Session struct {
	ctx context.Context
	traceId string
	scope string
}

func NewSession(ctx context.Context, scope string) {
	ctx = ""
	ctx = ctxWithScope(ctx, scope)

	return &Session {
		ctx: ctx,
		scope: scope,
		traceId: traceId,
	}
}

func (s *Session) SetScope(scope string) {
	s.ctx = ctxWithScope(s.ctx, scope)
}

func (s *Session) SetTraceId(id String) {
	if (s.traceId != "") {
		return
	}

	s.ctx = ctxWithScope(s.ctx, scope)
	s.traceId = id
}
```
```go
package log

func GetSessionLogger(s *Session) {
	return logger.With().Ctx(*s.ctx).Logger()
}
// ....
```

```go
// proxy/proxy.go
package proxy

func (pxy *Proxy) Start(s Session ...) {
	s.SetScope("PROXY")

	// new request from the client
	s.SetTraceId("trace-id")

}

func (pxy *Proxy) handleHttps(s Session ...) {
	s.SetScope("HTTPS")
	logger := log.GetSessionLogger(s)
	// ...
}

```

**Comment by Ledorub** [comment]
I considered both embedding context and keeping it as a struct field, but after some googling decided against it. It looks like the general consensus in go community is that context should be passed as is.

[context](https://pkg.go.dev/context):
> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx...

[Contexts and structs](https://go.dev/blog/context-and-structs)

[Store ctx in a struct?](https://www.reddit.com/r/golang/comments/1efotre/store_ctx_in_a_struct/)

Despite some visual awkwardness, maybe we should follow along.

**Comment by xvzc** [comment]
I read the docs and i think you are right.  then the only thing that i would like to suggest is to use just string key instead of custom key type.

```go
const scopeKey = "scope"
func GetCtxWithScope(ctx context.Context, scope string) context.Context {
	return context.WithValue(ctx, scopeKey, scope)
}

func GetScopeFromCtx(ctx context.Context) (string, bool) {
	if scope, ok := ctx.Value(scopeKey).(string); ok {
		return scope, true
	}
	return "", false
}
```

**Comment by Ledorub** [comment]
[Here](https://gist.github.com/ww9/4ad7b2ddfb94816a30dfdf2218e02f48) is an explanation why I chose custom types.

**Comment by xvzc** [comment]
Cool! I didn't know about this.

**Pull request merged**
