### PR TITLE
Rename readme_zh-cn.md to readme_zh-CN.md

### PR DESCRIPTION
**Pull request by awslawsl233**
Typo

### CODE REVIEW

**Comment by xvzc** [comment]
closing cuz i already solved it

**Comment by xvzc** [comment]
Hi awslawsl233, does CN really need to be uppercase? cuz i already changed
it to lowercase in the links of the readme files
if u need to, make another PR Thanks

**Comment by awslawsl233** [comment]
No, not very necessary.

**Comment by xvzc** [comment]
Ok, thanks.

**Pull request closed without merging**
