### PR TITLE
Fix packet processing

### LINKED ISSUE #145: Telegram stopped working after the latest update
After the latest update (0.10.7) I can't use Telegram and spoof-dpi at the same time.

tgb

When I turn spoof-dpi off everything is ok.

tga_

**OS**: macOS 10.13.6

**Version**: 0.10.7

P.S. Same with 0.10.8.

### PR DESCRIPTION
**Pull request by Ledorub**
- Fixes `HttpRequest.Tidy` breaking packets by removing a mandatory blank line between headers and payload, and adding the CRLF after the payload. [RFC 7230 2.1](https://www.rfc-editor.org/rfc/rfc7230#section-2.1)
- Fixes (in a somewhat ugly way) proxy not converting absolute URIs to relative for requests other than the first one.
  According to the [RFC 7230 5.3.2](https://www.rfc-editor.org/rfc/rfc7230#section-5.3.2), all requests to a proxy server must contain absolute URIs, which proxy server must convert to relative before forwarding the request, as implied by [5.3.1](https://www.rfc-editor.org/rfc/rfc7230#section-5.3.1).
- Fixes #145.

It seems to work as intended, but it would be better to verify.

### CODE REVIEW

**Comment by xvzc** [comment]
Maybe we should use separate `serve` function or http and https?

**Comment by xvzc** [comment]
Let me do this.

**Comment by Ledorub** [comment]
The thing is, that those manipulations are required only for packets incoming from clients or send from proxy to server. There is no need to modify response packets.

I force-pushed a small optimization, not to iterate the first 9 bytes of the packet twice.

**Comment by xvzc** [comment]
I thought this issue also could happend with some other http methods too. So it's maybe better to use `pkt.Tidy()` instead of checking if first 9 bytes equals to `POST http`

**Comment by Ledorub** [comment]
> So it's maybe better to use `pkt.Tidy()`

I agree.

> There must be some downside in performance

Well, technically, HTTP proxy is expected to parse request headers, and modify them if needed.

**Comment by xvzc** [comment]
Could you please review the changes in #230 ? or maybe you can continue this PR somehow similary to #230

**Comment by Ledorub** [comment]
> Could you please review the changes in #230

I left a question about arg names there.

**Comment by xvzc** [comment]
> I left a question about arg names there.

Can't see any comment there.

**Comment by Ledorub** [comment]
That's weird. I can see them in both "Conversation" and "Files changed" tabs. Both on the desktop web version and on mobile.

**Comment by xvzc** [comment]
image

Is this some kinda error or something? could you please try it again?

**Comment by Ledorub** [comment]
The conversation counter is also 0 for me, but under your top comment i see this:
Screenshot 2024-08-31 at 17 24 15
The same can be seen in the `Files changed` tab, under the quoted code lines.

**Comment by xvzc** [comment]
Maybe the pending label is the reason, i think we should submit the review to be shown to others.

1. the lConn, rConn naming was a mistake, i am going to change it
2. I actually don't think this is not DRY as currently it is. because that would be just one function call anyway whether we functionize that line or not.

**Comment by Ledorub** [comment]
> Maybe the pending label is the reason, i think we should submit the review to be shown to others.

I had no idea that it can't be seen by others, but after checking the page in incognito, it seems so.

> 2\. because that would be just one function call anyway

The same bit of code is used in:
- `deliverRequest`
- `deliverResponse`
- `communicate` (HTTPS)

**Comment by xvzc** [comment]
Ah, Okay. agreed. i will push it tomorrow. no more coding today it's my birthday! haha

**Comment by Ledorub** [comment]
NP.
Happy birthday!

**Pull request closed without merging**
